FROM node:16.20-buster-slim as builder
ARG VERSION=v1.7.4
ENV VERSION=${VERSION}

RUN set -ex \
    && git clone -b ${VERSION} --depth=1 https://github.com/1Panel-dev/1Panel /opt/1Panel

WORKDIR /opt/1Panel/frontend
RUN set -ex \
    && rm -f package-lock.json \
    && yarn add codemirror vue-codemirror \
    && yarn install \
    && yarn build \
    && rm -rf node_modules

WORKDIR /opt/1Panel
RUN set -ex \
    && mkdir -p dist web-${VERSION} \
    && cp -f cmd/server/web/index.html web-${VERSION}/index.html \
    && cp -R cmd/server/web/assets web-${VERSION}/assets \
    && tar -czf web-${VERSION}.tar.gz web-${VERSION} \
    && mv web-${VERSION}.tar.gz dist/ \
    && rm -rf web-${VERSION}

FROM debian:buster-slim

WORKDIR /opt/1Panel

COPY --from=builder /opt/1Panel/dist /opt/1Panel/dist

VOLUME /dist

CMD cp -rf dist/* /dist/


